if(NOT cp2k::LAPACK)
  add_library(cp2k::LAPACK INTERFACE IMPORTED)
endif()

if(NOT CP2K_LAPACK_LINK_LIBRARIES)
  if(CP2K_BLAS_VENDOR MATCHES "^Intel" OR CP2K_BLAS_VENDOR STREQUAL "MKL")
    find_package(onemkl-cp2k CONFIG)
    target_link_libraries(cp2k::LAPACK INTERFACE MKL::MKL)
    get_target_properties(CP2K_LAPACK_LINK_LIBRARIES MKL::MKL IMPORTED_LINK_INTERFACE_LIBRARIES)
  else()
    # Use CMake FindLAPACK module
    set(BLA_VENDOR ${CP2K_BLAS_VENDOR})
    set(BLA_PGKCONFIG_BLAS ON)
    find_package(LAPACK REQUIRED)
    target_link_libraries(cp2k::LAPACK INTERFACE LAPACK::LAPACK)
    set(CP2K_LAPACK_LINK_LIBRARIES ${LAPACK_LIBRARIES})
  endif()
else()
  target_link_libraries(cp2k::LAPACK INTERFACE ${CP2K_LAPACK_LINK_LIBRARIES})
endif()
