if(NOT cp2k::BLAS)
  add_library(cp2k::BLAS INTERFACE IMPORTED)
endif()

if(NOT CP2K_BLAS_LINK_LIBRARIES)
  if(CP2K_BLAS_VENDOR MATCHES "^Intel" OR CP2K_BLAS_VENDOR STREQUAL "MKL")
  find_package(onemkl-cp2k)
  target_link_libraries(cp2k::BLAS INTERFACE MKL::MKL)
  get_target_properties(CP2K_BLAS_LINK_LIBRARIES MKL::MKL IMPORTED_LINK_INTERFACE_LIBRARIES)
else()
  # Use CMake FindBLAS module
  set(BLA_VENDOR ${CP2K_BLAS_VENDOR})
  set(BLA_PGKCONFIG_BLAS ON)
  find_package(BLAS REQUIRED)
  target_link_libraries(cp2k::BLAS INTERFACE BLAS::BLAS)
  set(CP2K_BLAS_LINK_LIBRARIES ${BLAS_LIBRARIES})
endif()
  target_link_libraries(cp2k::BLAS INTERFACE ${CP2K_BLAS_LINK_LIBRARIES})
endif()
