if(NOT cp2k::BLAS)
  add_library(cp2k::BLAS INTERFACE IMPORTED)
endif()

if(CP2K_BLAS_VENDOR STREQUAL "Intel" OR CP2K_BLAS_VENDOR STREQUAL "MKL")
  find_package(onemkl-cp2k)
  target_link_libraries(cp2k::BLAS INTERFACE MKL::MKL)
else()
  # Use CMake FindBLAS module
  set(BLA_VENDOR ${CP2K_BLAS_VENDOR})
  set(BLA_PGKCONFIG_BLAS ON)
  find_package(BLAS REQUIRED)
  target_link_libraries(cp2k::BLAS INTERFACE BLAS::BLAS)
  set(CP2K_BLAS_LIBRARIES ${BLAS_LIBRARIES})
endif()
